DELETE FROM Tasks;
DELETE FROM Completed_tasks;
TRUNCATE TABLE Completed_tasks RESTART IDENTITY;
DROP TABLE IF EXISTS Completed_tasks;
DROP TABLE  IF EXISTS Tasks;
TRUNCATE TABLE Users RESTART IDENTITY;
DROP TABLE  IF EXISTS Users;
